### ISSUE TITLE
Subplots option doesn't show multiple charts when in bar charts using bokeh as renderer

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/pixiedust#192]

**Comment by DTAIEB** [comment]
Fixed as part of #219

**Comment by jessmantaro** [comment]
I still see this issue. Bokeh shows the "grouped" chart. I can show you.

**Comment by DTAIEB** [comment]
Closing as duplicate of #233
